### ISSUE TITLE
DX Improvement: make data export more consistent

### ISSUE THREAD

**Issue by kahlstrm** [Tietokilta/web#138]
Currently the [`generate_seeding_data.sh`](https://github.com/Tietokilta/web/blob/main/scripts/generate_seeding_data.sh)-script makes the export in some arbitrary order (based on Mongos hashes or something)?. This can then cause some odd legibility problems in [diffs/PRs](https://github.com/Tietokilta/web/pull/129/files#diff-1eb8c7fdd12b9ef05e86f07e8d2b46536c008581ce1303ea262b65e262f816f5)

Fix for this would be some sort of consistent sorting method for these, e.g. by `createdAt` field or something like this.

**Comment by joonatanaatos** [comment]
Migration to postgres will fix this.
