### ISSUE TITLE
Not found and error pages

### ISSUE THREAD

**Issue by joonatanaatos** [Tietokilta/web#153]
Copy Teemu Teekkari -esteratapeli from [old-new tik-web](https://github.com/Tietokilta/tikweb-frontend/blob/main/src/components/DinoGame.tsx)

The error page needs to be localized, which must be done client-side as NextJS doesn't support it by default (T. Kalle)

Design can be improvised (there is some existing error page implementation, but it can be changed to better fit the style)

It would be nice if the title of the error pages are obtained from the cms, but this is not required for now. 
https://nextjs.org/docs/pages/building-your-application/routing/custom-error

**Comment by MikaelSiidorow** [comment]
I added better i18n with next-international, so this should now be more doable I hope?

**Comment by kahlstrm** [comment]
Closed by #297
